# What is Numpy

NumPy is the fundamental package for scientific computing with Python. 
It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. 
It is implemented in C and Fortran so when calculations are **vectorized**, performance is very good.

So, in a nutshell:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

If you are a MATLAB&reg; user we recommend to read [Numpy for MATLAB Users](http://www.scipy.org/NumPy_for_Matlab_Users) and [Benefit of Open Source Python versus commercial packages](http://www.scipy.org/NumPyProConPage). 

I'm a supporter of the **Open Science Movement**, thus I humbly suggest you to take a look at the [Science Code Manifesto](http://sciencecodemanifesto.org/)

In [10]:
import numpy as np

In [11]:
a = np.arange(10).reshape(2, 5)
b = np.arange(20).reshape(5, 4)

In [15]:
a @ b  # Python 3.5+

array([[120, 130, 140, 150],
       [320, 355, 390, 425]])

# Getting Started with Numpy Arrays

NumPy's main object is the **homogeneous** ***multidimensional array***. It is a table of elements (usually numbers), all of the same type. 

In Numpy dimensions are called **axes**. 

The number of axes is called **rank**. 

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

To use `numpy` need to import the module it using of example:

In [2]:
import numpy as np  # naming import convention

### Terminology Assumption

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

### Reference Documentation

* On the web: [http://docs.scipy.org](http://docs.scipy.org)/

* Interactive help:

In [16]:
np.array?

If you're looking for something

In [17]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [18]:
np.con*?

#### Help is your friend

Whenever in doubt, there is the `help` function to the rescue

In [19]:
# For example, try 
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  the methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optiona

## Numpy Array Object

`NumPy` has a multidimensional array object called ndarray. It consists of two parts as follows:
   
   * The actual data
   * Some metadata describing the data
    
    
The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

<img src="images/ndarray_with_details.png" />

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [3]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [4]:
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [5]:
print('Type of v: ', type(v))
print('Type of M: ', type(M))

Type of v:  <class 'numpy.ndarray'>
Type of M:  <class 'numpy.ndarray'>


The difference between the `v` and `M` arrays is only their shapes. 

To do so, we could use the `numpy.shape` function:

In [12]:
print('Shape of v: ', np.shape(v))
print('Shape of M: ', np.shape(M))

Size of v:  (4,)
Size of M:  (2, 2)


Alternatively, We can get information about the shape of an array by using the `ndarray.shape` **property** :

In [10]:
v.shape, M.shape

((4,), (2, 2))

Equivalently, we can get information about the **size** of the two `ndarrays`, namely the *total number of elements* in the array.

In [13]:
print('Size of v:', v.size)
print('Size of M:', M.size)

Size of v: 4
Size of M: 4


#### More properties of the `numpy array`

In [32]:
M.itemsize # bytes per element

8

In [33]:
M.nbytes # number of bytes

32

In [34]:
M.ndim # number of dimensions

2

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. 

Instead we can use one of the many **functions** in `numpy` that generates arrays of different forms. 

Some of the more common are: 

* `np.arange`; 
* `np.linspace`; 
* `np.logspace`; 
* `np.mgrid`;
* `np.random.rand`;
* `np.diag`;
* `np.zeros`;
* `np.ones`;
* `np.empty`;
* `np.tile`.

### `np.arange`

In [15]:
x = np.arange(0, 10, 1) 
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# floating point step-wise range generatation
x = np.arange(-1, 1, 0.1)  
print(x)

[ -1.00000000e+00  -9.00000000e-01  -8.00000000e-01  -7.00000000e-01
  -6.00000000e-01  -5.00000000e-01  -4.00000000e-01  -3.00000000e-01
  -2.00000000e-01  -1.00000000e-01  -2.22044605e-16   1.00000000e-01
   2.00000000e-01   3.00000000e-01   4.00000000e-01   5.00000000e-01
   6.00000000e-01   7.00000000e-01   8.00000000e-01   9.00000000e-01]


### `np.linspace` and `np.logspace`

In [18]:
# using linspace, both end points **ARE included**
np.linspace(0, 10, 25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [36]:
np.logspace(0, np.e**2, 10, base=np.e)

array([  1.00000000e+00,   2.27278564e+00,   5.16555456e+00,
         1.17401982e+01,   2.66829540e+01,   6.06446346e+01,
         1.37832255e+02,   3.13263169e+02,   7.11980032e+02,
         1.61817799e+03])

### `np.mgrid`

In [21]:
x, y = np.mgrid[0:5, 0:5]  # similar to meshgrid in MATLAB

In [22]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [23]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `np.random.rand` & `np.random.randn`

In [24]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[ 0.33658948,  0.28564552,  0.73183017,  0.7395105 ,  0.66427382],
       [ 0.25942094,  0.43844615,  0.48250402,  0.24063916,  0.90171053],
       [ 0.51114245,  0.49587249,  0.61832302,  0.71996951,  0.22064571],
       [ 0.38625609,  0.44313367,  0.74975323,  0.57600147,  0.80771956],
       [ 0.84511666,  0.6064582 ,  0.62365173,  0.62766319,  0.80129396]])

In [25]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[ 0.65782724,  0.65168367,  0.58525852,  0.33781734, -0.00700978],
       [ 0.61574011,  0.59150639, -0.33797592, -0.2509655 ,  0.77237429],
       [-0.15693266, -0.38377945, -0.28140147,  0.90558314,  0.25437408],
       [-1.136108  ,  2.43964939,  0.28583627, -0.27540796, -0.57253111],
       [-0.79080395,  0.50525127,  2.1113386 , -0.33769711, -0.64914575]])

### `np.diag`

In [27]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### `np.eye`

In [50]:
# a diagonal matrix with ones on the main diagonal
np.eye(3)  # 3 is the 

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### `np.zeros` and `np.ones`

In [30]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### DIY

***Try by yourself*** the following commands:

    np.zeros((3,4))
    np.ones((3,4))
    np.empty((2,3))
    np.eye(5)
    np.diag(np.arange(5))
    np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

In [20]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
np.tile(np.array([[6, 7], [8, 9]]), (2,3))

array([[6, 7, 6, 7, 6, 7],
       [8, 9, 8, 9, 8, 9],
       [6, 7, 6, 7, 6, 7],
       [8, 9, 8, 9, 8, 9]])

In [23]:
np.empty((2,3))

array([[  0.00000000e+000,   1.49166824e-154,   2.12299954e-314],
       [  2.15856291e-314,   0.00000000e+000,   0.00000000e+000]])

## So, why is it useful then?

So far the `numpy.ndarray` looks awefully much like a Python **list** (or **nested list**). 

*Why not simply use Python lists for computations instead of creating a new array type?*

There are several reasons:

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
    - They do not support mathematical functions such as matrix and dot multiplications, etc. 
    - Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
    
    
* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created.
    
    
* Numpy arrays are memory efficient.
    - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

In [25]:
import numpy as np

In [26]:
L = range(1000)

In [27]:
%timeit [i**2 for i in L]

1000 loops, best of 3: 524 µs per loop


In [28]:
a = np.arange(1000)

In [29]:
%timeit a**2

The slowest run took 55.95 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.22 µs per loop


In [30]:
%timeit [element**2 for element in a]

1000 loops, best of 3: 342 µs per loop


## Exercises

### Simple arrays

* Create simple one and two dimensional arrays. First, redo the examples
from above. And then create your own.

* Use the functions `len`, `shape` and `ndim` on some of those arrays and
observe their output.

In [35]:
np.array?

In [33]:
v = np.array([1, 2., 3, 4], )

In [36]:
v.size

4

In [37]:
len(v)

4

In [39]:
np.shape(v)

(4,)

In [40]:
v.ndim

1

In [49]:
M = np.array([[1, 2, 4], [6, 7]])
M.shape

(2,)

In [50]:
M

array([[1, 2, 4], [6, 7]], dtype=object)

In [51]:
type(M[0])

list

In [47]:
len(M)

2

In [48]:
M.size

6

In [46]:
v.shape, v.reshape(2, 2).shape, v.shape

((4,), (2, 2), (4,))

### Creating arrays using functions

* Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

* Create different kinds of arrays with random numbers.

* Try setting the seed before creating an array with random values 
    - *hint*: use `np.random.seed`

* Look at the function `np.empty`. What does it do? When might this be
useful?

# Basic Data Type

You may have noticed that, in some instances, array elements are
displayed with a trailing dot (e.g. `2.` vs `2`). This is due to a
difference in the data-type used:

In [59]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [60]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

### Note

Different data-types allow us to store data more compactly in memory,
but most of the time we simply work with floating point numbers. Note
that, in the example above, NumPy auto-detects the data-type from the
input.

You can explicitly specify which data-type you want:

In [61]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

The **default** data type is floating point:

In [62]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

## Basic Data Types

    bool             | This stores boolean (True or False) as a bit

    inti             | This is a platform integer (normally either int32 or int64)
    int8             | This is an integer ranging from -128 to 127
    int16            | This is an integer ranging from -32768 to 32767
    int32            | This is an integer ranging from -2 ** 31 to 2 ** 31 -1
    int64            | This is an integer ranging from -2 ** 63 to 2 ** 63 -1
    
    uint8            | This is an unsigned integer ranging from 0 to 255
    uint16           | This is an unsigned integer ranging from 0 to 65535
    uint32           | This is an unsigned integer ranging from 0 to 2 ** 32 - 1
    uint64           | This is an unsigned integer ranging from 0 to 2 ** 64 - 1

    float16          | This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa
    float32          | This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa
    float64 or float | This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa
    complex64        | This is a complex number represented by two 32-bit floats (real and imaginary components)
    complex128       | This is a complex number represented by two 64-bit floats (real and imaginary components)
    (or complex)


## Conversions and Type Casting

In [63]:
np.float64(42)  # int to float

42.0

In [64]:
np.int8(42.0)  # float to int8

42

In [67]:
np.bool(42)  # int to bool

True

In [68]:
np.bool(0)   # "special" int to bool

False

In [69]:
np.bool(42.0)  # float to bool

True

In [70]:
np.float(True)  # bool to float

1.0

In [71]:
np.float(False)

0.0

In [72]:
np.arange(7, dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [74]:
np.int(42.0 + 1.j)  # complex to int

TypeError: can't convert complex to int

In [73]:
np.float(42.0 + 1.j)  # complex to float

TypeError: can't convert complex to float

In [75]:
np.float(42.0 + 0.j)  # complex to float

TypeError: can't convert complex to float

In [77]:
cn = np.complex(42.0)  # Btw, you can convert a float to a complex..
print(cn)

(42+0j)


In [79]:
# Extracting the Real part..
cn.real

42.0

In [80]:
# .. and the Imaginary part
cn.imag

0.0

## Numerical Types and Representation

The **numerical dtype** of an array should be selected very carefully, as it directly affects the numerical representation of elements, that is: 

   * the number of **bytes used; 
   * the *numerical range*

So, then: **What happens if I try to represent a number that is Out of range?**

Let's have a go with **integers**, i.e., `int8` and `uint8`

In [27]:
x = np.zeros(4, 'int8')  # Integer ranging from -128 to 127
x

array([0, 0, 0, 0], dtype=int8)

In [28]:
x[0] = 127
x

array([127,   0,   0,   0], dtype=int8)

In [29]:
x[0] = 128
x

array([-128,    0,    0,    0], dtype=int8)

In [30]:
x[1] = 129
x

array([-128, -127,    0,    0], dtype=int8)

In [31]:
x[2] = 257  # i.e. (128 x 2) + 1
x

array([-128, -127,    1,    0], dtype=int8)

In [32]:
ux = np.zeros(4, 'uint8')  # Integer ranging from 0 to 255
ux

array([0, 0, 0, 0], dtype=uint8)

In [33]:
ux[0] = 255
ux[1] = 256
ux[2] = 257
ux[3] = 513  # (256 x 2) + 1
ux

array([255,   0,   1,   1], dtype=uint8)

## Data Type Object

**Data type objects** are instances of the `numpy.dtype` class. 

Once again, arrays have a data type. 
<br>
To be precise, *every element* in a NumPy array has the same data type. 

The data type object can tell you the `size` of the data in bytes.
<br>
(**Recall**: The size in bytes is given by the `itemsize` attribute of the dtype class)

In [81]:
a = np.arange(7, dtype=np.uint16)
print('a itemsize: ', a.itemsize)
print('a.dtype.itemsize: ', a.dtype.itemsize)

a itemsize:  2
a.dtype.itemsize:  2


We may also have access to the `byteorder`, i.e. **Big Endian** or **Little Endian**

In [82]:
a.dtype.byteorder

'='

### Note:

**Byte Order** can be one of:

* `=	native`
* `<	little-endian`
* `>	big-endian`
* `|	not applicable`

### Character Codes

Character codes are included for backward compatibility with **Numeric**. 
<br>
Numeric is the predecessor of NumPy. Their use is not recommended, but these codes pop up in several places. 

Btw, You should instead use the **dtype** objects. 

    integer                     i
    Unsigned integer            u
    Single precision float      f
    Double precision float      d
    bool                        b
    complex                     D
    string                      S
    unicode                     U

In [53]:
s = 'Ω≈ç√©π'
print(s)

Ω≈ç√©π


In [57]:
%%python3 

s = 'Ω≈ç√©π'

In [58]:
s

'Ω≈ç√©π'

In [59]:
π = np.pi
print(π)

3.141592653589793


### `dtypes` properties

In [83]:
t = np.dtype('Float64')

In [84]:
t.char

'd'

In [85]:
t.type

numpy.float64

In [86]:
t.str

'<f8'

### `dtype` contructors

In [87]:
np.dtype(float)

dtype('float64')

In [88]:
np.dtype('f')

dtype('float32')

In [89]:
np.dtype('d')

dtype('float64')

In [90]:
np.dtype('f8')

dtype('float64')

In [91]:
np.dtype('Float64')

dtype('float64')

**Note**: A listing of all data type names can be found by calling `np.sctypeDict.keys()`

## Creating a Record of `dtype`

* Define the new record type

In [102]:
rt = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])

In [103]:
rt['name']  # see the difference with Python 2

dtype('<U40')

In [104]:
rt['numitems']

dtype('int32')

In [105]:
rt['price']

dtype('float32')

* Instantiate an array of `dtype` equal to `t` (record type)


In [106]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=rt)

In [64]:
np.array?

In [108]:
print(itemz)

[('Meaning of life DVD', 42, 3.140000104904175)
 ('Butter', 13, 2.7200000286102295)]


## Exercise

### Creating your own record type

* Practicing by creating your own record type

### Record Types and Array Creation

1. Create an array of elements whose type is a record defined as a couple of numbers. The first number refers to a ranking position, and the second one to a degree value.
2. Create an array of this new type, feeding the element from a dictionary, sorted with respect to the ranking positions.

## Tuple Unpacking

In [65]:
t = (1, 99)
r, d = t
print(r, d)

1 99


In [66]:
t = (1, 99, 77, 12.6, 's')
r, *rest, v = t

In [67]:
r

1

In [68]:
v 

's'

In [69]:
rest

[99, 77, 12.6]

In [70]:
v = t[1]

In [71]:
v

99

In [73]:
_, _, _, *rest = t

In [74]:
rest

[12.6, 's']

In [78]:
numbers = range(10)
for number in numbers:
    print(number)

0
1
2
3
4
5
6
7
8
9


In [87]:
numbers = range(0, 20, 2)
print(list(numbers))
for item in enumerate(numbers):
    index, value = item
    print('index: ', index, ' value: ', value )

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
index:  0  value:  0
index:  1  value:  2
index:  2  value:  4
index:  3  value:  6
index:  4  value:  8
index:  5  value:  10
index:  6  value:  12
index:  7  value:  14
index:  8  value:  16
index:  9  value:  18


In [88]:
numbers = range(0, 20, 2)
for index, value in enumerate(numbers):
    print('index: ', index, ' value: ', value )

index:  0  value:  0
index:  1  value:  2
index:  2  value:  4
index:  3  value:  6
index:  4  value:  8
index:  5  value:  10
index:  6  value:  12
index:  7  value:  14
index:  8  value:  16
index:  9  value:  18


In [99]:
values = (('1', '99.3'), ('2', '88.9'), ('3', '79.3'), ('4', '78.9'), ('5', '77.5'),
         ('6', '69.2'), ('7', '58.1'), ('8', '43.3'), ('9', '38.9'), ('10', '33.3'))

results = dict()
for ranking, degree in values:
    results[ranking] = float(degree)

In [163]:
results = {values}

In [164]:
results

{(('1', '99.3'),
  ('2', '88.9'),
  ('3', '79.3'),
  ('4', '78.9'),
  ('5', '77.5'),
  ('6', '69.2'),
  ('7', '58.1'),
  ('8', '43.3'),
  ('9', '38.9'),
  ('10', '33.3'))}

In [100]:
print(results)

{'1': 99.3, '4': 78.9, '2': 88.9, '9': 38.9, '3': 79.3, '7': 58.1, '8': 43.3, '5': 77.5, '6': 69.2, '10': 33.3}


In [156]:
rt = np.dtype([('degree', np.float32), ('ranking', 'uint8'), ('pos', 'U10')])

In [157]:
rt

dtype([('degree', '<f4'), ('ranking', 'u1'), ('pos', '<U10')])

In [158]:
np_results = np.zeros((10, ), dtype=rt)

In [159]:
np_results

array([(0.0, 0, ''), (0.0, 0, ''), (0.0, 0, ''), (0.0, 0, ''),
       (0.0, 0, ''), (0.0, 0, ''), (0.0, 0, ''), (0.0, 0, ''),
       (0.0, 0, ''), (0.0, 0, '')], 
      dtype=[('degree', '<f4'), ('ranking', 'u1'), ('pos', '<U10')])

In [146]:
results.keys()

dict_keys(['1', '4', '2', '9', '3', '7', '8', '5', '6', '10'])

In [147]:
results.values()

dict_values([99.3, 78.9, 88.9, 38.9, 79.3, 58.1, 43.3, 77.5, 69.2, 33.3])

In [148]:
results.items()

dict_items([('1', 99.3), ('4', 78.9), ('2', 88.9), ('9', 38.9), ('3', 79.3), ('7', 58.1), ('8', 43.3), ('5', 77.5), ('6', 69.2), ('10', 33.3)])

In [149]:
lkeys = [int(k) for k in results.keys()]
lkeys.sort()
print(lkeys)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [150]:
# def sort_string_key(item):
#     return int(item[0])
ordered_keys = sorted(results, key=lambda key: int(key))
print(ordered_keys)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']


In [160]:
for i, key in enumerate(ordered_keys):
    np_results[i] = (results[key], int(key), key)

In [161]:
np_results

array([(99.30000305175781, 1, '1'), (88.9000015258789, 2, '2'),
       (79.30000305175781, 3, '3'), (78.9000015258789, 4, '4'),
       (77.5, 5, '5'), (69.19999694824219, 6, '6'),
       (58.099998474121094, 7, '7'), (43.29999923706055, 8, '8'),
       (38.900001525878906, 9, '9'), (33.29999923706055, 10, '10')], 
      dtype=[('degree', '<f4'), ('ranking', 'u1'), ('pos', '<U10')])

In [162]:
d_results = dict(np_results)

ValueError: dictionary update sequence element #0 has length 3; 2 is required

In [154]:
d_results.keys()

dict_keys([33.299999, 99.300003, 69.199997, 38.900002, 88.900002, 58.099998, 43.299999, 77.5, 78.900002, 79.300003])

In [140]:
d_results.values()

dict_values([99.300003, 88.900002, 79.300003, 78.900002, 77.5, 69.199997, 58.099998, 43.299999, 38.900002, 33.299999])

In [141]:
type(d_results), type(d_results[1]), type(list(d_results.keys())[0])

(dict, numpy.float32, numpy.uint8)

In [165]:
s, *_, t = (1, 2, 5, 6, 7)

In [166]:
_

[2, 5, 6]