# Operations

In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib

In [2]:
df = pd.read_json('./data/sampledf.json')
df.index = ["R{:02d}".format(i) for i in range(len(df))]
df.columns = ["C{:02d}".format(i) for i in range(len(df.columns))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09
R00   79   19   21   99   35   59   44   25   75   58
R01   25   39   89   66    9   41    6   69   63    3
R02   37   64   31   69   61   97    5   11   76   57
R03   74   61  100    6   58   80   95   50   15   51
R04   79   60   83   85   16    5   16   69    5   20
R05   45   26   73   73  100   60   21   19   95   12
R06   12   29   18   98   62   68   92   29   74   96
R07   36   32   22    4   66   25   63   51   59   14
R08   55   53   89   13   84   87   74    3    2   64
R09   46   74   36   54   21   12   68   33   80   25

### Adding and deleting Series in a DataFrame

In [3]:
df['C10'] = [random.randint(1, 100) for i in range(len(df))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   71
R01   25   39   89   66    9   41    6   69   63    3   18
R02   37   64   31   69   61   97    5   11   76   57   89
R03   74   61  100    6   58   80   95   50   15   51   18
R04   79   60   83   85   16    5   16   69    5   20    1
R05   45   26   73   73  100   60   21   19   95   12   77
R06   12   29   18   98   62   68   92   29   74   96   74
R07   36   32   22    4   66   25   63   51   59   14   67
R08   55   53   89   13   84   87   74    3    2   64    5
R09   46   74   36   54   21   12   68   33   80   25   18

In [4]:
# caveat when adding a Series:
new_series = pd.Series(list([random.randint(1, 100) for i in range(len(df))]))
new_series

0    63
1    99
2    38
3    73
4    99
5    77
6    97
7    11
8    26
9    83
dtype: int64

In [5]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58  NaN
R01   25   39   89   66    9   41    6   69   63    3  NaN
R02   37   64   31   69   61   97    5   11   76   57  NaN
R03   74   61  100    6   58   80   95   50   15   51  NaN
R04   79   60   83   85   16    5   16   69    5   20  NaN
R05   45   26   73   73  100   60   21   19   95   12  NaN
R06   12   29   18   98   62   68   92   29   74   96  NaN
R07   36   32   22    4   66   25   63   51   59   14  NaN
R08   55   53   89   13   84   87   74    3    2   64  NaN
R09   46   74   36   54   21   12   68   33   80   25  NaN

In [6]:
# adding a new Series: mind the index of the DF
new_series.index = df.index
new_series

R00    63
R01    99
R02    38
R03    73
R04    99
R05    77
R06    97
R07    11
R08    26
R09    83
dtype: int64

In [7]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   63
R01   25   39   89   66    9   41    6   69   63    3   99
R02   37   64   31   69   61   97    5   11   76   57   38
R03   74   61  100    6   58   80   95   50   15   51   73
R04   79   60   83   85   16    5   16   69    5   20   99
R05   45   26   73   73  100   60   21   19   95   12   77
R06   12   29   18   98   62   68   92   29   74   96   97
R07   36   32   22    4   66   25   63   51   59   14   11
R08   55   53   89   13   84   87   74    3    2   64   26
R09   46   74   36   54   21   12   68   33   80   25   83

In [8]:
df['C11'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10  C11
R00   79   19   21   99   35   59   44   25   75   58   63   63
R01   25   39   89   66    9   41    6   69   63    3   99   99
R02   37   64   31   69   61   97    5   11   76   57   38   38
R03   74   61  100    6   58   80   95   50   15   51   73   73
R04   79   60   83   85   16    5   16   69    5   20   99   99
R05   45   26   73   73  100   60   21   19   95   12   77   77
R06   12   29   18   98   62   68   92   29   74   96   97   97
R07   36   32   22    4   66   25   63   51   59   14   11   11
R08   55   53   89   13   84   87   74    3    2   64   26   26
R09   46   74   36   54   21   12   68   33   80   25   83   83

In [9]:
del df['C11']
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   63
R01   25   39   89   66    9   41    6   69   63    3   99
R02   37   64   31   69   61   97    5   11   76   57   38
R03   74   61  100    6   58   80   95   50   15   51   73
R04   79   60   83   85   16    5   16   69    5   20   99
R05   45   26   73   73  100   60   21   19   95   12   77
R06   12   29   18   98   62   68   92   29   74   96   97
R07   36   32   22    4   66   25   63   51   59   14   11
R08   55   53   89   13   84   87   74    3    2   64   26
R09   46   74   36   54   21   12   68   33   80   25   83

In [10]:
del df['C12']

KeyError: 'C12'

In [11]:
# avoid KeyErrors if unsure Series exists
df.drop(['C12'], errors='ignore')

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   63
R01   25   39   89   66    9   41    6   69   63    3   99
R02   37   64   31   69   61   97    5   11   76   57   38
R03   74   61  100    6   58   80   95   50   15   51   73
R04   79   60   83   85   16    5   16   69    5   20   99
R05   45   26   73   73  100   60   21   19   95   12   77
R06   12   29   18   98   62   68   92   29   74   96   97
R07   36   32   22    4   66   25   63   51   59   14   11
R08   55   53   89   13   84   87   74    3    2   64   26
R09   46   74   36   54   21   12   68   33   80   25   83

In [12]:
# getting a subset is simpler than deleting many columns
dfs = df.loc[:, ['C03', 'C05']]
dfs

C03  C05
R00   99   59
R01   66   41
R02   69   97
R03    6   80
R04   85    5
R05   73   60
R06   98   68
R07    4   25
R08   13   87
R09   54   12

In [13]:
dfs['C04'] = [random.randint(1, 100) for i in range(len(df))]

In [14]:
dfs

C03  C05  C04
R00   99   59   47
R01   66   41   89
R02   69   97   67
R03    6   80    8
R04   85    5   79
R05   73   60   74
R06   98   68   23
R07    4   25   94
R08   13   87   97
R09   54   12   15

In [15]:
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   63
R01   25   39   89   66    9   41    6   69   63    3   99
R02   37   64   31   69   61   97    5   11   76   57   38
R03   74   61  100    6   58   80   95   50   15   51   73
R04   79   60   83   85   16    5   16   69    5   20   99
R05   45   26   73   73  100   60   21   19   95   12   77
R06   12   29   18   98   62   68   92   29   74   96   97
R07   36   32   22    4   66   25   63   51   59   14   11
R08   55   53   89   13   84   87   74    3    2   64   26
R09   46   74   36   54   21   12   68   33   80   25   83

### Mangle your data

**recall: NumPy Broadcasting**

In [16]:
a = np.random.rand(3,1)
a

array([[0.61903208],
       [0.76795317],
       [0.26790371]])

In [17]:
b = np.random.rand(3,1)
b

array([[0.58635195],
       [0.64208162],
       [0.12870538]])

In [18]:
a + b

array([[1.20538403],
       [1.41003479],
       [0.39660909]])

In [19]:
a - b

array([[0.03268013],
       [0.12587155],
       [0.13919833]])

In [20]:
a * b

array([[0.36297067],
       [0.49308861],
       [0.03448065]])

In [21]:
a / b

array([[1.05573466],
       [1.19603669],
       [2.08152693]])

In [22]:
a + 7

array([[7.61903208],
       [7.76795317],
       [7.26790371]])

In [23]:
b // 2

array([[0.],
       [0.],
       [0.]])

In [24]:
a % 2 == 0

array([[False],
       [False],
       [False]])

In [25]:
a * [4, 5]

array([[2.47612831, 3.09516039],
       [3.07181268, 3.83976585],
       [1.07161484, 1.33951855]])

### Broadcasting in Pandas

In [26]:
sales_data = pd.read_json('./data/blooth_sales_data.json',
                              convert_dates=['birthday', 'orderdate']
                              )
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  
0          Star Wars     27      11.81  
1        PlayStation      1     284.71  
2             banana     49      10.00  
3    Thriller record     48      16.77  
4  Harry Potter book      4       5.65

In [27]:
sales_data['turnover'] = sales_data['unitprice'] * sales_data['units']
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  
0          Star Wars     27      11.81    318.87  
1        PlayStation      1     284.71    284.71  
2             banana     49      10.00    490.00  
3    Thriller record     48      16.77    804.96  
4  Harry Potter book      4       5.65     22.60

In [28]:
sales_data['turnover'].mean()

59915.64764605545

In [29]:
class A:
    
    def __init__(self, a=0):
        self.a = a
        
    def __add__(self, o):
        return self.a + o.a
    
    


In [30]:
a = A(10)
b = A(20)

In [31]:
a + b

30

In [32]:
sales_data.mean()

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42585/590773150.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  sales_data.mean()
/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42585/590773150.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sales_data.mean()


units           25.808102
unitprice     2329.681343
turnover     59915.647646
dtype: float64

In [33]:
sales_data['turnover'].sum()

140502193.73000002

In [34]:
sales_data['turnover'].median()

532.14

In [35]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2345 entries, 0 to 2344
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   name       2345 non-null   object        
 1   birthday   2345 non-null   datetime64[ns]
 2   customer   2345 non-null   object        
 3   orderdate  2345 non-null   datetime64[ns]
 4   product    2345 non-null   object        
 5   units      2345 non-null   int64         
 6   unitprice  2345 non-null   float64       
 7   turnover   2345 non-null   float64       
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 146.7+ KB


### Excercise

Calculate the mean without using .mean

In [36]:
# your code here


Find the oldest customer (bithday)

In [37]:
# your code here


### Functions with **`.map(), .apply() .applymap()`**

In [38]:
# map for Series
sales_data['year'] = sales_data['orderdate'].map(lambda x: x.year)
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  
0          Star Wars     27      11.81    318.87  2016  
1        PlayStation      1     284.71    284.71  2016  
2             banana     49      10.00    490.00  2016  
3    Thriller record     48      16.77    804.96  2016  
4  Harry Potter book      4       5.65     22.60  2016

In [39]:
# map for Series
sales_data['month'] = sales_data['orderdate'].map(lambda x: x.month)
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month  
0          Star Wars     27      11.81    318.87  2016     10  
1        PlayStation      1     284.71    284.71  2016      9  
2             banana     49      10.00    490.00  2016     10  
3    Thriller record     48      16.77    804.96  2016     10  
4  Harry Potter book      4       5.65     22.60  2016     10

In [40]:
# combine multiple columns
sales_data['year-month'] = sales_data['year'].map(
    str) + sales_data['month'].map(lambda x: "-{:02d}".format(x))

In [41]:
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      11.81    318.87  2016     10    2016-10  
1        PlayStation      1     284.71    284.71  2016      9    2016-09  
2             banana     49      10.00    490.00  2016     10    2016-10  
3    Thriller record     48      16.77    804.96  2016     10    2016-10  
4  Harry Potter book      4       5.65     22.60  2016     10    2016-10

In [42]:
sales_data[['unitprice', 'units']].head()

unitprice  units
0      11.81     27
1     284.71      1
2      10.00     49
3      16.77     48
4       5.65      4

In [43]:
# applymap for df
sales_data[['unitprice', 'units']].applymap(lambda x: np.round(4 * x, 2)).head(5)

unitprice  units
0      47.24    108
1    1138.84      4
2      40.00    196
3      67.08    192
4      22.60     16

In [44]:
sales_data[['unitprice', 'units']].apply(lambda x: np.round(4 * x, 2)).head(5)

unitprice  units
0      47.24    108
1    1138.84      4
2      40.00    196
3      67.08    192
4      22.60     16

#####  Differences of **`.map(), .apply() .applymap()`**

 * **`.map()`**
 >iterate over each element of a DataFrame

In [45]:
sales_data['unitprice'].map(int)[:5]

0     11
1    284
2     10
3     16
4      5
Name: unitprice, dtype: int64

 * **`.apply()`**
 > apply a function on an axis of the DataFrame.

e.g. sum up two cells (hier: unitprice + units)

In [46]:
sales_data[['unitprice', 'units']].apply(sum, axis=1)[:5] # default axis=0

0     38.81
1    285.71
2     59.00
3     64.77
4      9.65
dtype: float64

 * **`.applymap()`** 
 > apply a function on each element of the DataFrame

In [47]:
sales_data[['unitprice', 'units']].applymap(int)[:5]

unitprice  units
0         11     27
1        284      1
2         10     49
3         16     48
4          5      4

#### Remember: a copy of the DF is returned. The DF is not altered.

In [48]:

sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      11.81    318.87  2016     10    2016-10  
1        PlayStation      1     284.71    284.71  2016      9    2016-09  
2             banana     49      10.00    490.00  2016     10    2016-10  
3    Thriller record     48      16.77    804.96  2016     10    2016-10  
4  Harry Potter book      4       5.65     22.60  2016     10    2016-10

In [49]:
sales_data['unitprice'] = sales_data['unitprice'].map(lambda x: x * 2)

In [50]:
sales_data.describe()

units     unitprice      turnover    year        month
count  2345.000000   2345.000000  2.345000e+03  2345.0  2345.000000
mean     25.808102   4659.362687  5.991565e+04  2016.0     9.812793
std      14.474110  13164.655228  1.969636e+05     0.0     0.390161
min       1.000000     10.020000  5.080000e+00  2016.0     9.000000
25%      13.000000     21.320000  2.601000e+02  2016.0    10.000000
50%      26.000000     35.700000  5.321400e+02  2016.0    10.000000
75%      39.000000    979.880000  1.016450e+04  2016.0    10.000000
max      50.000000  49791.260000  1.222270e+06  2016.0    10.000000

In [51]:
sales_data['birthday'].describe()

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42585/852887285.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  sales_data['birthday'].describe()


count                    2345
unique                    296
top       1998-04-20 00:00:00
freq                       19
first     1952-02-07 00:00:00
last      1999-05-01 00:00:00
Name: birthday, dtype: object

In [53]:
sales_data['turnover'] = sales_data['turnover'].astype(np.int32)
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      23.62       318  2016     10    2016-10  
1        PlayStation      1     569.42       284  2016      9    2016-09  
2             banana     49      20.00       490  2016     10    2016-10  
3    Thriller record     48      33.54       804  2016     10    2016-10  
4  Harry Potter book      4      11.30        22  2016     10    2016-10

In [55]:
sales_data[sales_data['unitprice'].isnull()]

Empty DataFrame
Columns: [name, birthday, customer, orderdate, product, units, unitprice, turnover, year, month, year-month]
Index: []

In [56]:
sales_data.dropna().head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      23.62       318  2016     10    2016-10  
1        PlayStation      1     569.42       284  2016      9    2016-09  
2             banana     49      20.00       490  2016     10    2016-10  
3    Thriller record     48      33.54       804  2016     10    2016-10  
4  Harry Potter book      4      11.30        22  2016     10    2016-10

In [57]:
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      23.62       318  2016     10    2016-10  
1        PlayStation      1     569.42       284  2016      9    2016-09  
2             banana     49      20.00       490  2016     10    2016-10  
3    Thriller record     48      33.54       804  2016     10    2016-10  
4  Harry Potter book      4      11.30        22  2016     10    2016-10

In [58]:
sales_data.fillna(99.99).head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      23.62       318  2016     10    2016-10  
1        PlayStation      1     569.42       284  2016      9    2016-09  
2             banana     49      20.00       490  2016     10    2016-10  
3    Thriller record     48      33.54       804  2016     10    2016-10  
4  Harry Potter book      4      11.30        22  2016     10    2016-10

In [59]:
sales_data.head()

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      23.62       318  2016     10    2016-10  
1        PlayStation      1     569.42       284  2016      9    2016-09  
2             banana     49      20.00       490  2016     10    2016-10  
3    Thriller record     48      33.54       804  2016     10    2016-10  
4  Harry Potter book      4      11.30        22  2016     10    2016-10

In [60]:
sales_data.fillna(99.99, inplace=True)
sales_data.head(5)

name   birthday               customer                  orderdate  \
0  Ernesto 1974-01-07    Frontier Industries 2016-10-06 08:21:20.544568   
1    Queen 1986-02-05   Bell Telecom Limited 2016-09-30 08:21:20.544599   
2     Reid 1982-07-06            Software Co 2016-10-05 08:21:20.544622   
3   Arlene 1971-04-12  Data Design Galaxy Co 2016-10-02 08:21:20.544643   
4   Nikita 1984-12-14           Frontier Inc 2016-10-16 08:21:20.544666   

             product  units  unitprice  turnover  year  month year-month  
0          Star Wars     27      23.62       318  2016     10    2016-10  
1        PlayStation      1     569.42       284  2016      9    2016-09  
2             banana     49      20.00       490  2016     10    2016-10  
3    Thriller record     48      33.54       804  2016     10    2016-10  
4  Harry Potter book      4      11.30        22  2016     10    2016-10