# What is Numpy

NumPy is the fundamental package for scientific computing with Python. 
It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. 
It is implemented in C and Fortran so when calculations are **vectorized**, performance is very good.

So, in a nutshell:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

If you are a MATLAB&reg; user we recommend to read [Numpy for MATLAB Users](http://www.scipy.org/NumPy_for_Matlab_Users) and [Benefit of Open Source Python versus commercial packages](http://www.scipy.org/NumPyProConPage). 

I'm a supporter of the **Open Science Movement**, thus I humbly suggest you to take a look at the [Science Code Manifesto](http://sciencecodemanifesto.org/)

In [1]:
import numpy as np

In [2]:
a = np.arange(10).reshape(2, 5)
b = np.arange(20).reshape(5, 4)

In [3]:
a @ b  # from Python 3.5+

array([[120, 130, 140, 150],
       [320, 355, 390, 425]])

# Getting Started with Numpy Arrays

NumPy's main object is the **homogeneous** ***multidimensional array***. It is a table of elements (usually numbers), all of the same type. 

In Numpy dimensions are called **axes**. 

The number of axes is called **rank**. 

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

To use `numpy` need to import the module it using of example:

In [4]:
import numpy as np  # naming import convention

### Terminology Assumption

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

### Reference Documentation

* On the web: [http://docs.scipy.org](http://docs.scipy.org)/

* Interactive help:

In [5]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

If you're looking for something

## Numpy Array Object

`NumPy` has a multidimensional array object called ndarray. It consists of two parts as follows:
   
   * The actual data
   * Some metadata describing the data
    
    
The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

<img src="images/ndarray_with_details.png" />

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [6]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [7]:
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [8]:
print('Type of v: ', type(v))
print('Type of M: ', type(M))

Type of v:  <class 'numpy.ndarray'>
Type of M:  <class 'numpy.ndarray'>


The difference between the `v` and `M` arrays is only their shapes. 

To do so, we could use the `numpy.shape` function:

In [9]:
print('Shape of v: ', np.shape(v))
print('Shape of M: ', np.shape(M))

Shape of v:  (4,)
Shape of M:  (2, 2)


Alternatively, We can get information about the shape of an array by using the `ndarray.shape` **property** :

In [10]:
v.shape, M.shape

((4,), (2, 2))

Equivalently, we can get information about the **size** of the two `ndarrays`, namely the *total number of elements* in the array.

In [11]:
print('Size of v:', v.size)
print('Size of M:', M.size)

Size of v: 4
Size of M: 4


#### More properties of the `numpy array`

In [12]:
M.itemsize # bytes per element

8

In [13]:
M.nbytes # number of bytes

32

In [14]:
M.ndim # number of dimensions

2

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. 

Instead we can use one of the many **functions** in `numpy` that generates arrays of different forms. 

Some of the more common are: 

* `np.arange`; 
* `np.linspace`; 
* `np.logspace`; 
* `np.mgrid`;
* `np.random.rand`;
* `np.diag`;
* `np.zeros`;
* `np.ones`;
* `np.empty`;
* `np.tile`.

### `np.arange`

In [15]:
x = np.arange(0, 10, 1) 
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# floating point step-wise range generatation
x = np.arange(-1, 1, 0.1)  
print(x)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


### `np.linspace` and `np.logspace`

In [17]:
# using linspace, both end points **ARE included**
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [18]:
np.logspace(0, np.e**2, 10, base=np.e)

array([1.00000000e+00, 2.27278564e+00, 5.16555456e+00, 1.17401982e+01,
       2.66829540e+01, 6.06446346e+01, 1.37832255e+02, 3.13263169e+02,
       7.11980032e+02, 1.61817799e+03])

### `np.mgrid`

In [19]:
x, y = np.mgrid[0:5, 0:5]  # similar to meshgrid in MATLAB

In [20]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [21]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `np.random.rand` & `np.random.randn`

In [22]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[0.17484598, 0.21196798, 0.6490131 , 0.60807481, 0.44996083],
       [0.20203773, 0.397198  , 0.2344878 , 0.16069716, 0.47784793],
       [0.34090367, 0.00558286, 0.25797409, 0.28038869, 0.40736219],
       [0.83866508, 0.37114091, 0.70040395, 0.59926472, 0.38160881],
       [0.34008559, 0.2494668 , 0.47583446, 0.13157778, 0.87325939]])

In [23]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[-1.78174872, -0.21984334, -0.05904113, -1.62313165, -0.27459672],
       [-1.43197599,  0.68155412,  0.87771014,  0.08415311, -0.89704524],
       [ 0.56436843,  0.70610462,  0.36303664, -0.78284051, -0.09891728],
       [ 1.22782386,  0.74164668, -1.54051946,  0.19502843, -1.3787375 ],
       [ 0.27494475, -0.05004675, -1.96920504,  1.49586677, -0.12651449]])

### `np.diag`

In [24]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### `np.eye`

In [26]:
# a diagonal matrix with ones on the main diagonal
np.eye(3)  # 3 is the 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### `np.zeros` and `np.ones`

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### DIY

***Try by yourself*** the following commands:

    np.zeros((3,4))
    np.ones((3,4))
    np.empty((2,3))
    np.eye(5)
    np.diag(np.arange(5))
    np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

In [29]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.tile(np.array([[6, 7], [8, 9]]), (2,3))

array([[6, 7, 6, 7, 6, 7],
       [8, 9, 8, 9, 8, 9],
       [6, 7, 6, 7, 6, 7],
       [8, 9, 8, 9, 8, 9]])

In [31]:
np.empty((2,3))

array([[0.e+000, 7.e-323, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

## So, why is it useful then?

So far the `numpy.ndarray` looks awefully much like a Python **list** (or **nested list**). 

*Why not simply use Python lists for computations instead of creating a new array type?*

There are several reasons:

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
    - They do not support mathematical functions such as matrix and dot multiplications, etc. 
    - Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
    
    
* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created.
    
    
* Numpy arrays are memory efficient.
    - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

In [32]:
import numpy as np

In [33]:
L = range(1000)

In [34]:
%timeit [i**2 for i in L]

362 µs ± 7.73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [35]:
a = np.arange(1000)

In [36]:
%timeit a**2

1.43 µs ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [37]:
%timeit [element**2 for element in a]

273 µs ± 4.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Exercises

### Simple arrays

* Create simple one and two dimensional arrays. First, redo the examples
from above. And then create your own.

* Use the functions `len`, `shape` and `ndim` on some of those arrays and
observe their output.

### Creating arrays using functions

* Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

* Create different kinds of arrays with random numbers.

* Try setting the seed before creating an array with random values 
    - *hint*: use `np.random.seed`

* Look at the function `np.empty`. What does it do? When might this be
useful?

# Basic Data Type

You may have noticed that, in some instances, array elements are
displayed with a trailing dot (e.g. `2.` vs `2`). This is due to a
difference in the data-type used:

In [38]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [39]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

### Note

Different data-types allow us to store data more compactly in memory,
but most of the time we simply work with floating point numbers. Note
that, in the example above, NumPy auto-detects the data-type from the
input.

You can explicitly specify which data-type you want:

In [40]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

The **default** data type is floating point:

In [41]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

## Basic Data Types

    bool             | This stores boolean (True or False) as a bit

    inti             | This is a platform integer (normally either int32 or int64)
    int8             | This is an integer ranging from -128 to 127
    int16            | This is an integer ranging from -32768 to 32767
    int32            | This is an integer ranging from -2 ** 31 to 2 ** 31 -1
    int64            | This is an integer ranging from -2 ** 63 to 2 ** 63 -1
    
    uint8            | This is an unsigned integer ranging from 0 to 255
    uint16           | This is an unsigned integer ranging from 0 to 65535
    uint32           | This is an unsigned integer ranging from 0 to 2 ** 32 - 1
    uint64           | This is an unsigned integer ranging from 0 to 2 ** 64 - 1

    float16          | This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa
    float32          | This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa
    float64 or float | This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa
    complex64        | This is a complex number represented by two 32-bit floats (real and imaginary components)
    complex128       | This is a complex number represented by two 64-bit floats (real and imaginary components)
    (or complex)


In [42]:
np.float64(42)  # int to float

42.0

In [43]:
np.int8(42.0)  # float to int8

42

In [44]:
np.bool(42)  # int to bool

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42353/4280509913.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool(42)  # int to bool


True

In [45]:
np.bool(0)   # "special" int to bool

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42353/3670249838.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool(0)   # "special" int to bool


False

In [46]:
np.bool(42.0)  # float to bool

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42353/1609167945.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool(42.0)  # float to bool


True

In [47]:
np.float(True)  # bool to float

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42353/4157332417.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(True)  # bool to float


1.0

In [48]:
np.float(False)

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42353/2166875113.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(False)


0.0

In [49]:
np.arange(7, dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [50]:
np.int(42.0 + 1.j)  # complex to int

/var/folders/16/xdrp9d8s5510rt6fwr4j6llr0000gn/T/ipykernel_42353/548987334.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.int(42.0 + 1.j)  # complex to int


TypeError: can't convert complex to int

In [ ]:
np.float(42.0 + 1.j)  # complex to float

In [ ]:
np.float(42.0 + 0.j)  # complex to float

In [ ]:
cn = np.complex(42.0)  # Btw, you can convert a float to a complex..
print(cn)

In [ ]:
# Extracting the Real part..
cn.real

In [ ]:
# .. and the Imaginary part
cn.imag

## Numerical Types and Representation

The **numerical dtype** of an array should be selected very carefully, as it directly affects the numerical representation of elements, that is: 

   * the number of **bytes used; 
   * the *numerical range*

So, then: **What happens if I try to represent a number that is Out of range?**

Let's have a go with **integers**, i.e., `int8` and `uint8`

In [51]:
x = np.zeros(4, 'int8')  # Integer ranging from -128 to 127
x

array([0, 0, 0, 0], dtype=int8)

In [52]:
x[0] = 127
x

array([127,   0,   0,   0], dtype=int8)

In [53]:
x[0] = 128
x

array([-128,    0,    0,    0], dtype=int8)

In [54]:
x[1] = 129
x

array([-128, -127,    0,    0], dtype=int8)

In [55]:
x[2] = 257  # i.e. (128 x 2) + 1
x

array([-128, -127,    1,    0], dtype=int8)

In [56]:
ux = np.zeros(4, 'uint8')  # Integer ranging from 0 to 255
ux

array([0, 0, 0, 0], dtype=uint8)

In [57]:
ux[0] = 255
ux[1] = 256
ux[2] = 257
ux[3] = 513  # (256 x 2) + 1
ux

array([255,   0,   1,   1], dtype=uint8)

## Data Type Object

**Data type objects** are instances of the `numpy.dtype` class. 

Once again, arrays have a data type. 
<br>
To be precise, *every element* in a NumPy array has the same data type. 

The data type object can tell you the `size` of the data in bytes.
<br>
(**Recall**: The size in bytes is given by the `itemsize` attribute of the dtype class)

In [58]:
a = np.arange(7, dtype=np.uint16)
print('a itemsize: ', a.itemsize)
print('a.dtype.itemsize: ', a.dtype.itemsize)

a itemsize:  2
a.dtype.itemsize:  2


We may also have access to the `byteorder`, i.e. **Big Endian** or **Little Endian**

In [59]:
a.dtype.byteorder

'='

### Note:

**Byte Order** can be one of:

* `=	native`
* `<	little-endian`
* `>	big-endian`
* `|	not applicable`

### Character Codes

Character codes are included for backward compatibility with **Numeric**. 
<br>
Numeric is the predecessor of NumPy. Their use is not recommended, but these codes pop up in several places. 

Btw, You should instead use the **dtype** objects. 

    integer                     i
    Unsigned integer            u
    Single precision float      f
    Double precision float      d
    bool                        b
    complex                     D
    string                      S
    unicode                     U

In [60]:
s = 'Ω≈ç√©π'
print(s)

Ω≈ç√©π


In [61]:
%%python3 

s = 'Ω≈ç√©π'

In [62]:
s

'Ω≈ç√©π'

In [63]:
π = np.pi
print(π)

3.141592653589793


### `dtypes` properties

In [64]:
t = np.dtype('Float64')

TypeError: data type 'Float64' not understood

In [65]:
t.char

NameError: name 't' is not defined

In [66]:
t.type

NameError: name 't' is not defined

In [67]:
t.str

NameError: name 't' is not defined

### `dtype` contructors

In [68]:
np.dtype(float)

dtype('float64')

In [69]:
np.dtype('f')

dtype('float32')

In [70]:
np.dtype('d')

dtype('float64')

In [71]:
np.dtype('f8')

dtype('float64')

In [72]:
np.dtype('Float64')

TypeError: data type 'Float64' not understood

**Note**: A listing of all data type names can be found by calling `np.sctypeDict.keys()`

## Creating a Record of `dtype`

* Define the new record type

In [73]:
rt = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])

In [74]:
rt['name']  # see the difference with Python 2

dtype('<U40')

In [75]:
rt['numitems']

dtype('int32')

In [76]:
rt['price']

dtype('float32')

* Instantiate an array of `dtype` equal to `t` (record type)


In [77]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=rt)

In [78]:
print(itemz)

[('Meaning of life DVD', 42, 3.14) ('Butter', 13, 2.72)]


## Exercise

### Creating your own record type

* Practicing by creating your own record type
